# Generated by Django 5.0.6 on 2024-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('idlibro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del libro')),
                ('portada', models.ImageField(upload_to='imagenes/', verbose_name='Portada del libro')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor del libro')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial del libro')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion del libro')),
            ],
        ),
    ]
